openapi: 3.0.0
info:
  title: Billing API
  version: 1.0.0
paths:
  /invoices:
    post:
      summary: Generate a new invoice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: integer
      responses:
        '200':
          description: Invoice generated successfully
